apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: {{ .Release.Name }}-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
  namespace: {{ .Release.Name }}-ns
spec: 
  rules: 
    - host: preview-{{ .Release.Name }}.agriaku.com
      http: 
        paths: 
          - path: /
            pathType: Prefix
            backend: 
              service:
                name: {{ .Release.Name }}-svc
                port: 
                  number: 8080