apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Name }}-ns
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort:  {{ .Values.ports.containerPort }}
  selector:
    {{- include "preview-chart.selectorLabels" . | nindent 4 }}